In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [2]:
data = pd.read_csv("jester-data-1.csv",header = None)
d = data.to_latex()
text_file = open("Output_1.txt", "w")
text_file.write(d)
text_file.close()

In [3]:

train, validate, test = np.split(data, [int(.8*len(data)), int(.9*len(data))])
#print (train)
del train[0]

In [4]:
n_features = 2

user_ratings = train.values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))


In [5]:
latent_user_preferences

array([[ 0.427,  0.266],
       [ 0.823,  0.326],
       [ 0.568,  0.467],
       ..., 
       [ 0.716,  0.453],
       [ 0.654,  0.34 ],
       [ 0.02 ,  0.368]])

In [6]:
latent_item_features

array([[ 0.859,  0.691],
       [ 0.236,  0.023],
       [ 0.154,  0.849],
       [ 0.621,  0.575],
       [ 0.302,  0.285],
       [ 0.105,  0.529],
       [ 0.115,  0.418],
       [ 0.329,  0.039],
       [ 0.809,  0.805],
       [ 0.791,  0.629],
       [ 0.204,  0.267],
       [ 0.906,  0.074],
       [ 0.435,  0.059],
       [ 0.341,  0.542],
       [ 0.471,  0.014],
       [ 0.701,  0.767],
       [ 0.559,  0.308],
       [ 0.183,  0.514],
       [ 0.17 ,  0.222],
       [ 0.64 ,  0.494],
       [ 0.306,  0.068],
       [ 0.727,  0.495],
       [ 0.542,  0.764],
       [ 0.723,  0.725],
       [ 0.359,  0.332],
       [ 0.151,  0.234],
       [ 0.887,  0.078],
       [ 0.324,  0.249],
       [ 0.016,  0.058],
       [ 0.475,  0.061],
       [ 0.041,  0.482],
       [ 0.742,  0.755],
       [ 0.504,  0.144],
       [ 0.739,  0.157],
       [ 0.986,  0.498],
       [ 0.485,  0.37 ],
       [ 0.361,  0.747],
       [ 0.841,  0.527],
       [ 0.798,  0.73 ],
       [ 0.91 ,  0.913],


In [7]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating- rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(rating!=99):
                    err = train(user_id,item_id,rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if(iteration%1 == 0 ):
            print mse
                    

In [8]:
sgd()

26.0966279631
25.1037342469
24.7772725183
24.5361698065
24.3055392612
24.0742490519
23.8411563128
23.6072645707
23.37418156
23.1436828378


In [9]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 0.881,  0.533,  0.533, ...,  0.981,  0.415,  1.344],
       [ 1.064,  0.654,  0.621, ...,  1.259,  0.503,  1.678],
       [ 1.92 ,  1.152,  1.181, ...,  2.073,  0.904,  2.881],
       ..., 
       [ 1.999,  1.206,  1.217, ...,  2.2  ,  0.942,  3.03 ],
       [ 1.365,  0.827,  0.823, ...,  1.529,  0.644,  2.089],
       [ 0.844,  0.493,  0.548, ...,  0.815,  0.395,  1.195]])

In [10]:
values = [zip(user_ratings[i], predictions[i]) for i in range(0,predictions.shape[0])]                                                            
comparison_data = pd.DataFrame(values)
del data[0]
comparison_data.columns = data.columns
comparison_data.applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

1                2                3                4    \
0       (-7.820|0.881)    (8.790|0.533)   (-9.660|0.533)  (-8.160|-0.509)   
1        (4.080|1.064)   (-0.290|0.654)    (6.360|0.621)   (4.370|-0.585)   
2       (99.000|1.920)   (99.000|1.152)   (99.000|1.181)  (99.000|-1.136)   
3       (99.000|1.347)    (8.350|0.822)   (99.000|0.800)  (99.000|-0.759)   
4        (8.500|1.699)    (4.610|1.001)   (-4.170|1.085)  (-5.390|-1.060)   
5      (-6.170|-0.252)  (-3.540|-0.164)   (0.440|-0.129)   (-8.500|0.114)   
6       (99.000|1.172)   (99.000|0.689)   (99.000|0.752)  (99.000|-0.735)   
7        (6.840|0.533)    (3.160|0.297)    (9.170|0.375)  (-6.210|-0.379)   
8       (-3.790|1.380)   (-3.540|0.800)   (-9.420|0.907)  (-6.890|-0.895)   
9        (3.010|1.302)    (5.150|0.783)    (5.150|0.797)   (3.010|-0.765)   
10      (-2.910|1.482)    (4.080|0.904)   (99.000|0.880)  (99.000|-0.836)   
11       (1.310|1.120)    (1.800|0.654)    (2.570|0.726)  (-2.380|-0.713)   
12      (99.000|1.433)   (99.000|0.841)   (99.000|0.919)  (99.000|-0.900)   
13       (9.220|1.606)    (9.270|0.974)    (9.220|0.965)   (8.300|-0.920)   
14       (8.790|0.199)   (-5.780|0.132)    (6.020|0.095)   (3.690|-0.081)   
15      (-3.500|1.396)    (1.550|0.843)    (2.330|0.847)  (-4.130|-0.811)   
16      (99.000|1.472)   (-9.270|0.894)   (99.000|0.883)  (99.000|-0.842)   
17       (3.160|1.232)    (7.620|0.740)    (3.790|0.756)   (8.250|-0.727)   
18       (4.220|0.391)    (3.640|0.237)   (99.000|0.236)  (99.000|-0.226)   
19      (99.000|1.581)    (7.620|0.943)   (99.000|0.983)  (99.000|-0.950)   
20       (2.570|0.346)   (-0.730|0.213)   (99.000|0.202)  (99.000|-0.190)   
21       (7.280|1.837)    (5.390|1.104)   (99.000|1.127)  (99.000|-1.084)   
22       (2.720|1.122)    (4.170|0.668)    (6.500|0.701)  (-3.540|-0.679)   
23       (2.090|1.574)   (-7.570|0.960)    (4.170|0.935)  (-8.400|-0.888)   
24      (-3.930|1.682)   (-1.170|1.016)    (2.280|1.019)  (-0.440|-0.975)   
25      (99.000|1.705)    (5.490|1.011)    (3.450|1.074)  (99.000|-1.044)   
26      (99.000|1.242)    (5.830|0.740)   (99.000|0.775)  (99.000|-0.750)   
27       (0.490|0.955)    (0.150|0.562)    (0.150|0.610)  (-9.560|-0.596)   
28      (99.000|1.108)   (99.000|0.646)   (99.000|0.720)  (99.000|-0.708)   
29      (99.000|1.459)    (4.080|0.875)   (99.000|0.899)  (99.000|-0.865)   
...                ...              ...              ...              ...   
19956    (8.740|1.378)    (7.860|0.829)   (-9.320|0.844)  (-9.510|-0.810)   
19957    (6.410|1.215)    (3.980|0.717)   (99.000|0.773)  (99.000|-0.754)   
19958   (-5.190|0.546)   (-5.920|0.317)    (6.550|0.358)  (-6.840|-0.354)   
19959   (99.000|1.733)   (99.000|1.031)   (99.000|1.086)  (99.000|-1.052)   
19960   (99.000|1.776)   (99.000|1.061)   (99.000|1.103)  (99.000|-1.066)   
19961   (-1.550|1.592)    (0.530|0.922)    (8.540|1.049)   (1.940|-1.036)   
19962  (-8.010|-0.285)  (-7.720|-0.178)  (-8.880|-0.161)    (8.350|0.149)   
19963    (9.270|1.141)   (-6.460|0.672)    (9.130|0.727)  (-8.500|-0.709)   
19964   (99.000|1.425)    (6.700|0.850)   (-8.690|0.887)  (99.000|-0.858)   
19965   (99.000|0.755)   (99.000|0.453)   (99.000|0.465)  (99.000|-0.448)   
19966   (-1.600|1.263)    (3.540|0.777)   (-1.990|0.736)  (-0.390|-0.693)   
19967    (6.360|0.712)   (-0.340|0.442)   (-4.170|0.406)  (-9.560|-0.378)   
19968   (99.000|1.998)    (8.980|1.208)   (99.000|1.209)   (9.130|-1.156)   
19969   (-0.440|0.819)   (-0.290|0.491)   (-0.440|0.505)   (2.620|-0.486)   
19970    (0.580|0.573)   (-0.780|0.334)    (0.830|0.372)  (-1.020|-0.365)   
19971    (3.690|1.059)    (5.190|0.630)    (4.810|0.661)  (99.000|-0.640)   
19972    (4.220|1.303)    (0.290|0.780)    (4.130|0.807)  (-9.810|-0.778)   
19973   (-2.140|1.251)   (-6.410|0.737)   (-3.830|0.799)  (-3.930|-0.780)   
19974    (4.270|2.242)    (5.830|1.343)    (5.830|1.384)   (4.270|-1.334)   
19975    (4.220|0.658)    (2.820|0.399)    (2.860|0.396)  (-3.790|-0.378)   
19976   (99.000

In [ ]:
comparison_data

1                         2    \
0       (-7.82, 0.880993387637)    (8.79, 0.532999755714)   
1          (4.08, 1.0639904023)   (-0.29, 0.654321725113)   
2         (99.0, 1.91981451044)     (99.0, 1.15214886414)   
3          (99.0, 1.3469110347)     (8.35, 0.82188853978)   
4           (8.5, 1.6992475002)     (4.61, 1.00051323507)   
5      (-6.17, -0.252217767225)  (-3.54, -0.163764560918)   
6         (99.0, 1.17217951296)    (99.0, 0.688715630734)   
7        (6.84, 0.533064098455)    (3.16, 0.297245936939)   
8        (-3.79, 1.37995811604)   (-3.54, 0.800233580398)   
9         (3.01, 1.30184486942)     (5.15, 0.78321081965)   
10       (-2.91, 1.48162257022)    (4.08, 0.903816816658)   
11        (1.31, 1.11978727541)     (1.8, 0.654218037737)   
12        (99.0, 1.43272746836)    (99.0, 0.841499228692)   
13        (9.22, 1.60558221023)    (9.27, 0.974374288904)   
14       (8.79, 0.198943525919)   (-5.78, 0.132475458758)   
15         (-3.5, 1.3957368638)      (1.55, 0.8428156023)   
16        (99.0, 1.47242302975)   (-9.27, 0.894223891664)   
17        (3.16, 1.23209864049)    (7.62, 0.740264007861)   
18       (4.22, 0.390905298919)     (3.64, 0.23651396564)   
19         (99.0, 1.5805477383)    (7.62, 0.943314693306)   
20       (2.57, 0.345525158371)   (-0.73, 0.212520444373)   
21        (7.28, 1.83744160797)     (5.39, 1.10400225834)   
22        (2.72, 1.12193929797)    (4.17, 0.668069681569)   
23        (2.09, 1.57411314085)   (-7.57, 0.960185989343)   
24       (-3.93, 1.68152990055)    (-1.17, 1.01617335474)   
25        (99.0, 1.70494246587)     (5.49, 1.01093460254)   
26        (99.0, 1.24204325969)     (5.83, 0.73991715003)   
27       (0.49, 0.955189526255)    (0.15, 0.562348284237)   
28        (99.0, 1.10781812178)    (99.0, 0.646419476252)   
29        (99.0, 1.45881869823)    (4.08, 0.874758625905)   
...                         ...                       ...   
19956      (8.74, 1.3784085015)    (7.86, 0.829145288905)   
19957       (6.41, 1.215210102)    (3.98, 0.716825513671)   
19958   (-5.19, 0.545859731674)   (-5.92, 0.316708736062)   
19959     (99.0, 1.73300711549)      (99.0, 1.0305245844)   
19960     (99.0, 1.77600660362)     (99.0, 1.06071632029)   
19961    (-1.55, 1.59242817946)    (0.53, 0.922474998122)   
19962  (-8.01, -0.284578573787)   (-7.72, -0.17756630458)   
19963     (9.27, 1.14056361951)   (-6.46, 0.672333982322)   
19964     (99.0, 1.42517603683)     (6.7, 0.850105998118)   
19965    (99.0, 0.755094157052)    (99.0, 0.452807180936)   
19966     (-1.6, 1.26299938829)     (3.54, 0.77729926648)   
19967    (6.36, 0.711684760787)   (-0.34, 0.442386891065)   
19968     (99.0, 1.99795677223)       (8.98, 1.208401864)   
19969   (-0.44, 0.818877950816)   (-0.29, 0.490826041262)   
19970    (0.58, 0.572847936996)   (-0.78, 0.334419061142)   
19971     (3.69, 1.05855439542)     (5.19, 0.63044138146)   
19972     (4.22, 1.30305180864)    (0.29, 0.779513400626)   
19973    (-2.14, 1.25112166534)   (-6.41, 0.736671706218)   
19974     (4.27, 2.24242262916)     (5.83, 1.34327550568)   
19975    (4.22, 0.657677400733)    (2.82, 0.398735149282)   
19976     (99.0, 1.39442514703)    (99.0, 0.831275861534)   
19977     (9.27, 1.21715431542)   (-4.95, 0.732626747223)   
19978    (4.37, 0.266652936082)   (-7.14, 0.160677694682)   
19979   (-5.63, 0.808731574133)   (-4.95, 0.469325675321)   
19980     (99.0, 1.38397572661)    (99.0, 0.812200286137)   
19981    (1.55, 0.310598178833)   (-3.45, 0.179625741614)   
19982     (99.0, 1.35556463973)    (99.0, 0.835149120999)   
19983    (-0.68, 1.99941953027)    (-4.56, 1.20576239907)   
19984     (99.0, 1.36522430817)    (99.0, 0.827180330621)   
19985     (2.04, 0.84393777966)   (-2.23, 0.492653080981)   

                            3                         4    \
0       (-9.66, 0.532778248334)  (-8.16, -0.509312082135)   
1        (6.36, 0.621199313878)   (4.37, -0.585208820067)   
2         (99.0, 1.18057926071)    (99.0, -1.13617521952)   
3

In [ ]:
d = comparison_data.to_latex()
text_file = open("comparison_1.txt", "w")
text_file.write(d)
text_file.close()